# Generated by Django 5.0.4 on 2024-04-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название песни')),
                ('composer', models.CharField(max_length=255, verbose_name='Исполнитель')),
                ('musical_genre', models.CharField(max_length=255, verbose_name='Музыкальный жанр')),
                ('theme', models.CharField(blank=True, max_length=255, verbose_name='Смысл песни')),
                ('year_of_creation', models.IntegerField(blank=True)),
            ],
        ),
    ]
