# Generated by Django 5.0.4 on 2024-04-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='year_of_creation',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
